name: CI - Linting WorkFlow

on:
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  linting:
    name: Check the code format using linting process
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint main
    - name: Lint with flake8
      run: |
        flake8 main.py
  
  deploy:
    name: Build docker image and push to aws ECR
    needs: linting
    runs-on: ubuntu-latest